version: "2"
services:
  # Collector
  otel-collector:
    image: otel/opentelemetry-collector
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OLTP HTTP receiver
      - "55679:55679" # zpages extension

  # prometheus:
  #   container_name: prometheus
  #   image: prom/prometheus:latest
  #   restart: always
  #   volumes:
  #     - ./prometheus.yaml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "9090:9090"